package org.ziyad.login.chatcanal;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Set;

@Document
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class ChatCanal {

    @Id
    private String canalId; //auto-generated by MongoDB
    private String canalName; //leave it to support chatting between multiple users later on
    private Set<String> recipients; //list of chat recipients' usernames

}
